### ISSUE TITLE
Duplicate user profile

### ISSUE THREAD

**Issue by jbampton** [NextCommunity/NextCommunity.github.io#155]
Duplicate profile seen in list

https://nextcommunity.github.io/network/

And here:

https://nextcommunity.github.io/network/0xMRTT/

https://nextcommunity.github.io/network/rubiin/

And both link to the same GitHub profile

https://github.com/0xMRTT/

**Comment by eugene4545** [comment]
hello, can i be assigned to this?

**Comment by eugene4545** [comment]
It seems like this might have been an oversight when the user updated their profile link. I suggest deleting the older profile link, since the newer one seems to be more up-to-date.

**Comment by jbampton** [comment]
Thanks !
