### ISSUE TITLE
CSS align top for avatar

### ISSUE THREAD

**Issue by jbampton** [NextCommunity/NextCommunity.github.io#27]
https://maxbase.org/network/majalian/

<img width="1094" alt="Screen Shot 2021-06-17 at 9 12 27 pm" src="https://user-images.githubusercontent.com/418747/122386118-e4844700-cfb0-11eb-9156-04322f1ee5df.png">

**Comment by ajakov** [comment]
@jbampton how is the html for the table generated?

**Comment by BaseMax** [comment]
> @jbampton how is the html for the table generated?

https://github.com/BaseMax/NextCommunity/blob/main/_layouts/network.md

**Comment by jbampton** [comment]
Done
