### ISSUE TITLE
Fix: need clear:both at the footer file, since we have float for the `ul.accounts li`

### ISSUE THREAD

**Issue by BaseMax** [NextCommunity/NextCommunity.github.io#28]

**Comment by BaseMax** [comment]
![bug](https://user-images.githubusercontent.com/2658040/122389862-a2dea680-cf86-11eb-8028-8150c7c49f4e.png)

There is a short line at top of the page. that is the `<hr>` tag at the footer file.

**Comment by eugene4545** [comment]
can i work on the issue?

**Comment by jbampton** [comment]
Hi @eugene4545 is this issue still valid ?

**Comment by eugene4545** [comment]
Hello @jbampton , it seems the issue may have been resolved. Please let me know if it persists. Thanks!
