### ISSUE TITLE
Please can I join this organisation?

### ISSUE THREAD

**Issue by CodingSpecies** [NextCommunity/NextCommunity.github.io#66]
Is it possible for me to join this organisation please? Thank you.
#65

**Comment by BaseMax** [comment]
Welcome.

**Comment by CodingSpecies** [comment]
Thank you

**Comment by CodingSpecies** [comment]
I am not sure, but I can't see the invite. Thanks

**Comment by CodingSpecies** [comment]
Any update @BaseMax? thanks

**Comment by BaseMax** [comment]
Sorry for the delay.

@CodingSpecies Welcome.

**Comment by CodingSpecies** [comment]
Thank you
