### ISSUE TITLE
Automate repositories list tables at /about/open-source/

### ISSUE THREAD

**Issue by BaseMax** [NextCommunity/NextCommunity.github.io#7]
I need a help.
https://maxbase.org/about/open-source/

How we can automate this list?

I already wrote its script. so mostly ready: https://github.com/BaseMax/GitHub-Repository-Export-List

- open-source.main is input and main file.
GitHub actions should generate/update `open-source.md` file and replace  `{{{ TABLES }}}` with updated HTML TABLE.

**Comment by jbampton** [comment]
Maybe we can use the Jekyll data folder and create a CSV data file or similar with your script.

A GitHub action can be run with cron at certain times too.

Then just use standard liquid for loop to output the `table`

**Comment by jbampton** [comment]
This is an old issue.

Since we are now a community site perhaps we should close this issue ?

**Comment by BaseMax** [comment]
Yes, I agreed. close
