### ISSUE TITLE
Broken profile deleted from GitHub

### ISSUE THREAD

**Issue by jbampton** [NextCommunity/NextCommunity.github.io#99]
<img width="314" alt="Screen Shot 2022-05-22 at 3 35 50 pm" src="https://user-images.githubusercontent.com/418747/169680497-56bca899-ed40-4acc-808f-682644a9b59d.png">
<img width="877" alt="Screen Shot 2022-05-22 at 3 35 35 pm" src="https://user-images.githubusercontent.com/418747/169680499-da841cc2-c775-462b-b9a3-4da44e11e9ba.png">

**Comment by BaseMax** [comment]
https://github.com/rjphares, he/she deleted the account or renamed.

**Comment by BaseMax** [comment]
We can mail him to ask about it. Can you do that?

**Comment by jbampton** [comment]
Fixed
